import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import globals from 'globals'

export default tseslint.config(
  // Global ignores: build output and config files generated by tooling.
  { ignores: ['dist', 'node_modules', '*.tsbuildinfo'] },

  // Base JS rules: catch syntax issues that tsc doesn't (e.g. empty blocks).
  js.configs.recommended,

  // TypeScript: type-checked lint rules. We piggyback on `tsc -b` for the
  // full type-check pass; ESLint just adds the recommended style/quality
  // rules on top.
  ...tseslint.configs.recommended,

  // Project-wide overrides.
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // React Hooks: critical correctness rules. Both on warn — they catch
      // real bugs (effect deps, stale closures) without false positives.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // Fast Refresh: enforce that files only export React components so
      // HMR doesn't blow away state on edit.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // TypeScript overrides: we want unused vars caught but `_`-prefixed
      // params (common in callbacks) and React import (used for JSX) OK.
      '@typescript-eslint/no-unused-vars': ['warn', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
      }],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'error',

      // Allow non-null assertions where we've already null-checked (the
      // codebase uses `value!.toFixed(1)` patterns intentionally).
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  // Relax a few rules in build/tooling files.
  {
    files: ['vite.config.ts', '**/*.config.{js,ts}'],
    languageOptions: { globals: { ...globals.node } },
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
    },
  },
)