apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitorbeat.fullname" . }}-web
  labels: {{- include "monitorbeat.labels" . | nindent 4 }}
data:
  web.yaml: |
{{ toYaml .Values.monitorweb.config | indent 4 }}
