apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "monitorbeat.fullname" . }}-beat
  labels: {{- include "monitorbeat.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: beat
      {{- include "monitorbeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-monitorbeat.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: beat
        {{- include "monitorbeat.selectorLabels" . | nindent 8 }}
    spec:
      hostPID: true
      {{- with .Values.monitorbeat.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitorbeat.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "monitorbeat.fullname" . }}-beat
        - name: host-proc
          hostPath:
            path: /proc
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-root
          hostPath:
            path: /
      containers:
        - name: monitorbeat
          image: "{{ .Values.monitorbeat.image }}"
          imagePullPolicy: {{ .Values.monitorbeat.pullPolicy }}
          securityContext:
            capabilities:
              add:
                - NET_RAW
          args:
            - -config
            - /etc/monitorbeat/config.yaml
            {{- with .Values.monitorbeat.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MONITORBEAT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: /host/proc
            - name: HOST_SYS
              value: /host/sys
            {{- with .Values.monitorbeat.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/monitorbeat/config.yaml
              subPath: monitorbeat.yaml
              readOnly: true
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
            - name: host-sys
              mountPath: /host/sys
              readOnly: true
            - name: host-root
              mountPath: /host
              readOnly: true
          resources: {{ toYaml .Values.monitorbeat.resources | nindent 12 }}
