apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitorbeat.fullname" . }}-web
  labels: {{- include "monitorbeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.monitorweb.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
      {{- include "monitorbeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-monitorweb.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: web
        {{- include "monitorbeat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.monitorweb.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitorweb.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "monitorbeat.fullname" . }}-web
        - name: data
        {{- if .Values.monitorweb.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.monitorweb.persistence.existingClaim }}
        {{- else if .Values.monitorweb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "monitorbeat.fullname" . }}-web-data
        {{- else }}
          emptyDir: {}
        {{- end }}
      containers:
        - name: monitorweb
          image: "{{ .Values.monitorweb.image }}"
          imagePullPolicy: {{ .Values.monitorweb.pullPolicy }}
          args:
            - -config
            - /etc/monitorweb/config.yaml
          ports:
            - containerPort: 8080
              name: http
          startupProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /etc/monitorweb/config.yaml
              subPath: web.yaml
              readOnly: true
            - name: data
              mountPath: /data
          resources: {{ toYaml .Values.monitorweb.resources | nindent 12 }}
